### ISSUE TITLE
終了済みのPostが表示できない

### ISSUE THREAD

**Issue by sniper-fly** [42supporters-hackason/pair-pro#138]
unmatchedPostが、

１）未マッチング

２）マッチング済み

３）ペアプロ終了

３）のPostを表示できるようにする

**Comment by tacomeet** [comment]
3
`myCompletedPosts` 

か

`status` っていうカラムを `Post` に持たせて、 `myPosts` でフィルタリング出来るようにする

**Comment by sniper-fly** [comment]
status 案は良いと思いますが、かなり規模の大きな変更になるので、別チケットにします。
