### ISSUE TITLE
アプリの使い方説明の文言の見直し

### ISSUE THREAD

**Issue by sniper-fly** [42supporters-hackason/pair-pro#166]
みんなで議論しよう！！

**Comment by taisei-13046** [comment]
コミュニティについて
<img width="541" alt="スクリーンショット 2022-08-24 22 21 39" src="https://user-images.githubusercontent.com/78260526/186429367-b1c7d853-7747-4ae3-87b7-706c6f04e2e9.png">

**Comment by taisei-13046** [comment]
ドライバーとナビゲータについて
<img width="525" alt="スクリーンショット 2022-08-24 22 22 36" src="https://user-images.githubusercontent.com/78260526/186429510-b49ad85c-ba11-4a1d-9467-ff70344455c1.png">
<img width="530" alt="スクリーンショット 2022-08-24 22 22 47" src="https://user-images.githubusercontent.com/78260526/186429557-4f9ac1e6-8884-4939-b93d-f595b3a45bb5.png">

**Comment by taisei-13046** [comment]
マッチングした後の流れ
<img width="516" alt="スクリーンショット 2022-08-24 22 23 33" src="https://user-images.githubusercontent.com/78260526/186429757-1a784266-52d5-41b3-8852-1406175b8f0b.png">

**Comment by sniper-fly** [comment]
> ドライバーとナビゲータについて <img alt="スクリーンショット 2022-08-24 22 22 36" width="525" src="https://user-images.githubusercontent.com/78260526/186429510-b49ad85c-ba11-4a1d-9467-ff70344455c1.png"> <img alt="スクリーンショット 2022-08-24 22 22 47" width="530" src="https://user-images.githubusercontent.com/78260526/186429557-4f9ac1e6-8884-4939-b93d-f595b3a45bb5.png">

ここの説明、改善の余地がありそうな気がしますね。
https://gist.github.com/j5ik2o/2970973

ナビゲーター(見てる人)
ドライバー(キーボードを打つ人)

みたいに、一般的な説明から入っていって、このサービスではドライバーが募集を作成することから始まりますよ、みたいな文言の方がいいかもしれないです。
また明日きちんと文言考えてみます。
