### ISSUE TITLE
MessageのCRUD

### ISSUE THREAD

**Issue by sniper-fly** [42supporters-hackason/pair-pro#33]
チャットの実装

**Comment by tacomeet** [comment]
https://codesandbox.io/s/nexus-example-subscriptions-59kdb
これが一番他の実装と合ってそう。ただpubsubだけだとメッセージ保管されないよね？

**Comment by tacomeet** [comment]
https://www.apollographql.com/docs/apollo-server/v2/data/subscriptions#production-pubsub-libraries

apolloのPubSubは使わない方が良いらしい

**Comment by tacomeet** [comment]
v2だとあるけど、v3だと消えてる
https://www.apollographql.com/docs/apollo-server/v2/data/subscriptions
https://www.apollographql.com/docs/apollo-server/data/subscriptions/

> Subscriptions are not currently supported in [Apollo Federation](https://www.apollographql.com/docs/federation/).

**Comment by tacomeet** [comment]
> https://www.apollographql.com/docs/apollo-server/v2/data/subscriptions#production-pubsub-libraries
> 
> apolloのPubSubは使わない方が良いらしい

in-memoryで動くから、複数のサーバーのインスタンスがあるときに、動かなくなるっぽい。
